name = "S.G.U";
picture = "SGU_Patch_x512_512.paa";
logoSmall = "SGU_Patch_x64_64.paa";
logo = "SGU_Patch_x64_64.paa";
logoOver = "SGU_Patch_x64_64.paa";
action = "http://www.swedish-gaming-unit.se/";
actionName = "Website";
tooltip = "S.G.U";
tooltipOwned = "S.G.U";
dlcColor[] = {1, 0.76, 0, 1};
overview = "<a href='http://www.swedish-gaming-unit.se/'>Swedish-Gaming-Unit</a>, SGU contains custom items and improvements for the community group SGU. <br/><br/>Created by Trox.";
hideName = 0;
hidePicture = 0;